version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: agent-netbox:latest
    container_name: agent-netbox-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped 